using System.Collections.Generic;

namespace EzDbCodeGen.Interfaces.Schema
{
    /// <summary>
    /// Defines a table in a database schema.
    /// </summary>
    public interface ITable
    {
        /// <summary>
        /// Gets the name of the table.
        /// </summary>
        string Name { get; }

        /// <summary>
        /// Gets the schema name of the table.
        /// </summary>
        string Schema { get; }

        /// <summary>
        /// Gets the full name of the table including the schema (e.g., "dbo.Customer").
        /// </summary>
        string FullName { get; }

        /// <summary>
        /// Gets the description or comment of the table.
        /// </summary>
        string Description { get; }

        /// <summary>
        /// Gets a value indicating whether this table is a view.
        /// </summary>
        bool IsView { get; }

        /// <summary>
        /// Gets a value indicating whether this table is a junction table in a many-to-many relationship.
        /// </summary>
        bool IsJunctionTable { get; }

        /// <summary>
        /// Gets the columns in this table.
        /// </summary>
        IReadOnlyCollection<IColumn> Columns { get; }

        /// <summary>
        /// Gets the primary key columns for this table.
        /// </summary>
        IReadOnlyCollection<IColumn> PrimaryKeyColumns { get; }

        /// <summary>
        /// Gets the foreign keys defined on this table.
        /// </summary>
        IReadOnlyCollection<IForeignKey> ForeignKeys { get; }

        /// <summary>
        /// Gets the unique constraints defined on this table.
        /// </summary>
        IReadOnlyCollection<IUniqueConstraint> UniqueConstraints { get; }

        /// <summary>
        /// Gets the indexes defined on this table.
        /// </summary>
        IReadOnlyCollection<IIndex> Indexes { get; }

        /// <summary>
        /// Gets a column by its name.
        /// </summary>
        /// <param name="columnName">The name of the column to get.</param>
        /// <returns>The column with the specified name, or null if no such column exists.</returns>
        IColumn GetColumn(string columnName);

        /// <summary>
        /// Gets a value indicating whether this table has a primary key.
        /// </summary>
        bool HasPrimaryKey { get; }

        /// <summary>
        /// Gets a value indicating whether the primary key is auto-generated (e.g., identity column).
        /// </summary>
        bool HasAutoGeneratedPrimaryKey { get; }
    }
}
