<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EzDbCodeGen.Core\EzDbCodeGen.Core.csproj" />
    <ProjectReference Include="..\EzDbCodeGen.Schema\EzDbCodeGen.Schema.csproj" />
    <ProjectReference Include="..\EzDbCodeGen.TypeMapping\EzDbCodeGen.TypeMapping.csproj" />
    <ProjectReference Include="..\EzDbCodeGen.TemplateEngine\EzDbCodeGen.TemplateEngine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
