using System;
using System.Collections.Generic;
using System.Linq;
using EzDbCodeGen.Interfaces.Schema;

namespace EzDbCodeGen.Core.Schema.Models
{
    /// <summary>
    /// Implementation of the ITable interface representing a table in a database schema.
    /// </summary>
    public class Table : ITable
    {
        private readonly List<IColumn> _columns = new();
        private readonly List<IForeignKey> _foreignKeys = new();
        private readonly List<IUniqueConstraint> _uniqueConstraints = new();
        private readonly List<IIndex> _indexes = new();

        /// <summary>
        /// Initializes a new instance of the <see cref="Table"/> class.
        /// </summary>
        /// <param name="name">The name of the table.</param>
        /// <param name="schema">The schema name of the table.</param>
        public Table(string name, string schema)
        {
            Name = name ?? throw new ArgumentNullException(nameof(name));
            Schema = schema ?? throw new ArgumentNullException(nameof(schema));
        }

        /// <inheritdoc/>
        public string Name { get; }

        /// <inheritdoc/>
        public string Schema { get; }

        /// <inheritdoc/>
        public string FullName => $"{Schema}.{Name}";

        /// <inheritdoc/>
        public string Description { get; set; } = string.Empty;

        /// <inheritdoc/>
        public bool IsView { get; set; }

        /// <inheritdoc/>
        public bool IsJunctionTable { get; set; }

        /// <inheritdoc/>
        public IReadOnlyCollection<IColumn> Columns => _columns.AsReadOnly();

        /// <inheritdoc/>
        public IReadOnlyCollection<IColumn> PrimaryKeyColumns => 
            _columns.Where(c => c.IsPrimaryKey).OrderBy(c => c.OrdinalPosition).ToList().AsReadOnly();

        /// <inheritdoc/>
        public IReadOnlyCollection<IForeignKey> ForeignKeys => _foreignKeys.AsReadOnly();

        /// <inheritdoc/>
        public IReadOnlyCollection<IUniqueConstraint> UniqueConstraints => _uniqueConstraints.AsReadOnly();

        /// <inheritdoc/>
        public IReadOnlyCollection<IIndex> Indexes => _indexes.AsReadOnly();

        /// <inheritdoc/>
        public bool HasPrimaryKey => PrimaryKeyColumns.Any();

        /// <inheritdoc/>
        public bool HasAutoGeneratedPrimaryKey => PrimaryKeyColumns.Any(c => c.IsIdentity);

        /// <inheritdoc/>
        public IColumn? GetColumn(string columnName)
        {
            if (string.IsNullOrEmpty(columnName))
            {
                throw new ArgumentException("Column name cannot be null or empty.", nameof(columnName));
            }

            return _columns.FirstOrDefault(c => string.Equals(c.Name, columnName, StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Adds a column to the table.
        /// </summary>
        /// <param name="column">The column to add.</param>
        public void AddColumn(IColumn column)
        {
            if (column == null)
            {
                throw new ArgumentNullException(nameof(column));
            }

            if (_columns.Any(c => string.Equals(c.Name, column.Name, StringComparison.OrdinalIgnoreCase)))
            {
                throw new InvalidOperationException($"Column '{column.Name}' already exists in table '{FullName}'.");
            }

            _columns.Add(column);
        }

        /// <summary>
        /// Adds a foreign key to the table.
        /// </summary>
        /// <param name="foreignKey">The foreign key to add.</param>
        public void AddForeignKey(IForeignKey foreignKey)
        {
            if (foreignKey == null)
            {
                throw new ArgumentNullException(nameof(foreignKey));
            }

            if (_foreignKeys.Any(fk => string.Equals(fk.Name, foreignKey.Name, StringComparison.OrdinalIgnoreCase)))
            {
                throw new InvalidOperationException($"Foreign key '{foreignKey.Name}' already exists in table '{FullName}'.");
            }

            _foreignKeys.Add(foreignKey);
        }

        /// <summary>
        /// Adds a unique constraint to the table.
        /// </summary>
        /// <param name="uniqueConstraint">The unique constraint to add.</param>
        public void AddUniqueConstraint(IUniqueConstraint uniqueConstraint)
        {
            if (uniqueConstraint == null)
            {
                throw new ArgumentNullException(nameof(uniqueConstraint));
            }

            if (_uniqueConstraints.Any(uc => string.Equals(uc.Name, uniqueConstraint.Name, StringComparison.OrdinalIgnoreCase)))
            {
                throw new InvalidOperationException($"Unique constraint '{uniqueConstraint.Name}' already exists in table '{FullName}'.");
            }

            _uniqueConstraints.Add(uniqueConstraint);
        }

        /// <summary>
        /// Adds an index to the table.
        /// </summary>
        /// <param name="index">The index to add.</param>
        public void AddIndex(IIndex index)
        {
            if (index == null)
            {
                throw new ArgumentNullException(nameof(index));
            }

            if (_indexes.Any(i => string.Equals(i.Name, index.Name, StringComparison.OrdinalIgnoreCase)))
            {
                throw new InvalidOperationException($"Index '{index.Name}' already exists in table '{FullName}'.");
            }

            _indexes.Add(index);
        }

        /// <summary>
        /// Returns a string that represents the current object.
        /// </summary>
        /// <returns>A string that represents the current object.</returns>
        public override string ToString()
        {
            return FullName;
        }
    }
}
